---
title: "runoff_volumes"
author: "Charles Hendrickson"
date: "8/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)

# Source your storm_runoff.R script so you are able to use the predict_runoff function in your .Rmd
source(here::here("src", "storm_runoff.R"))
```

```{r}
# In a code chunk in your runoff_volumes.Rmd, use your predict_runoff function to estimate stormwater volume for a watershed of 182 acres, over a range of estimates for the impervious fraction (from 0.6 to 0.8, by increments of 0.01).

# My sequence
range_imperv_frac <- seq(from = 0.6, to = 0.8, by = 0.01)

# Using my function to create values for my data frame. 
data_runoff <- predict_runoff(182, range_imperv_frac)

# Bind your sequence of impervious fractions together with the resulting runoff volume calculated into a data frame

# My data frame:
df <- data.frame(data = data_runoff, range_imperv_frac)

# Create a ggplot graph that has both dots and connecting lines (i.e., you’ll layer geom_point() and geom_line(). Update axis labels. Export a png of your graph to the figs folder using ggsave.

runoff_volume_plot <- ggplot(data = df, aes(x = range_imperv_frac, y = data_runoff)) +
  geom_point() +
  geom_line() +
  xlab("Impervious fractions")+
  ylab("storm runoff volume")  

ggsave(here("figs", "Runoff_volume_plot.png"), plot = runoff_volume_plot
)
```

















